apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: projectns
type: Opaque
data:
  username: YXBwdXNlcg==        # appuser
  password: U3Ryb25nUGFzc3dvcmQxMjM= # StrongPassword123    
