apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: projectns
data:
  DB_HOST: postgres-postgresql.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
