apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
  namespace: projectns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
        - name: phoenix
          image: arizephoenix/phoenix:latest
          ports:
            - containerPort: 6006

          envFrom:
            - configMapRef:
                name: phoenix-config

          env:
            - name: PHOENIX_SQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phoenix-secret
                  key: PHOENIX_SQL_DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  namespace: projectns
spec:
  selector:
    app: phoenix
  ports:
    - port: 6006
      targetPort: 6006
  type: ClusterIP
